# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobManagement',
            fields=[
                ('nn_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(default=b'', max_length=10)),
                ('request', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default=b'', max_length=3)),
                ('progress', models.CharField(blank=True, default=b'', max_length=3)),
                ('acc', models.CharField(blank=True, default=b'', max_length=5)),
                ('epoch', models.CharField(blank=True, default=b'', max_length=20)),
                ('testsets', models.CharField(blank=True, default=b'', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NNInfo',
            fields=[
                ('nn_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('subcate', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('desc', models.CharField(blank=True, default=b'', max_length=5000)),
                ('type', models.CharField(blank=True, default=b'', max_length=100)),
                ('acc', models.CharField(blank=True, default=b'', max_length=5)),
                ('train', models.CharField(blank=True, default=b'', max_length=1)),
                ('config', models.CharField(blank=True, default=b'', max_length=1)),
                ('dir', models.CharField(blank=True, default=b'', max_length=200)),
                ('table', models.CharField(blank=True, default=b'', max_length=100)),
                ('query', models.CharField(blank=True, default=b'', max_length=5000)),
                ('datadesc', models.CharField(blank=True, default=b'', max_length=50000)),
                ('datasets', models.CharField(blank=True, default=b'', max_length=50000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerConf',
            fields=[
                ('version', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, default=b'', max_length=1)),
                ('store_type', models.CharField(blank=True, default=b'', max_length=10)),
                ('fw_capa', models.CharField(blank=True, default=b'', max_length=5)),
                ('livy_host', models.CharField(blank=True, default=b'', max_length=100)),
                ('livy_sess', models.CharField(blank=True, default=b'', max_length=5)),
                ('spark_host', models.CharField(blank=True, default=b'', max_length=100)),
                ('spark_core', models.CharField(blank=True, default=b'', max_length=5)),
                ('spark_memory', models.CharField(blank=True, default=b'', max_length=10)),
                ('hdfs_host', models.CharField(blank=True, default=b'', max_length=100)),
                ('hdfs_root', models.CharField(blank=True, default=b'', max_length=50)),
                ('s3_host', models.CharField(blank=True, default=b'', max_length=100)),
                ('s3_access', models.CharField(blank=True, default=b'', max_length=100)),
                ('s3_sess', models.CharField(blank=True, default=b'', max_length=100)),
                ('s3_bucket', models.CharField(blank=True, default=b'', max_length=100)),
            ],
        ),
    ]
